name: Playwright Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
    - name: Install dependencies
      run: npm ci
    - name: Install system dependencies for Playwright (all browsers)
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          # Core deps (Chromium/Firefox/WebKit shared)
          libasound2t64 \
          libatk1.0-0 \
          libcups2t64 \
          libdbus-1-3 \
          libdrm2 \
          libgbm1 \
          libglib2.0-0 \
          libgtk-3-0 \
          libnspr4 \
          libnss3 \
          libu2f-udev \
          libvulkan1 \
          libx11-6 \
          libx11-xcb1 \
          libxcb1 \
          libxcomposite1 \
          libxdamage1 \
          libxext6 \
          libxfixes3 \
          libxrandr2 \
          libxshmfence1 \
          libxss1 \
          libxtst6 \
          fonts-liberation \
          libffi8 \
          libx264-164 \
          # WebKit extras
          libwoff1 \
          libvpx-dev \
          libevent-2.1-7 \
          libopus0 \
          libharfbuzz-icu0 \
          gstreamer1.0-libav \
          gstreamer1.0-plugins-base \
          gstreamer1.0-plugins-good \
          gstreamer1.0-plugins-bad \
          gstreamer1.0-plugins-ugly \
          gstreamer1.0-alsa \
          gstreamer1.0-gl \
          gstreamer1.0-gtk3 \
          gstreamer1.0-plugins-base-apps \
          gstreamer1.0-pulseaudio \
          libsecret-1-0 \
          libhyphen0 \
          libmanette-0.2-0 \
          flite \
          libgles2


    - name: Install Playwright Browsers
      run: npx playwright install
    - name: Run Playwright tests
      run: npx playwright test
    - uses: actions/upload-artifact@v4
      if: always()
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
